version: "3"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    volumes:
      - C:\Users\Глеб\rebrain\db\data:/var/lib/postgresql/data
  app:
    image: .
    entrypoint: /usr/bin/start
    ports:
      - 8080:8080
