version: '3'
services:
  pgdb:
    image: "postgres:11"
    container_name: "pgdb"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
    ports:
      - "54320:5432"
    volumes:
      - C:\Users\Глеб\rebrain\db\data:/var/lib/postgresql/data